### PR TITLE
docs: Add custom media session attributes docs to readme

### PR DESCRIPTION
**Pull request by schallock**
## Summary
- Adds explanation of and examples for custom media session attributes

## Testing Plan
- This is only a docs change, no testing needed

## Reference Issue
- Closes https://go.mparticle.com/work/REPLACEME

### CODE REVIEW

**Review by jasonmgeorge — APPROVED** [review]
Looks good. No comments

**Comment by jasonmgeorge** [comment]
@einsteinx2 do we need to update to address any of these semantic release failures?

**Comment by einsteinx2** [comment]
@jasonmgeorge So all the semantic stuff is just complaining about branch and PR name rules, which is fine. The unit tests aren't running because for some reason due to needing a token to check out Eric's branch (which doesn't make sense to me since it's public), but since it's a docs only change that also doesn't matter.

**Review by einsteinx2 — APPROVED** [review]
lgtm

**Pull request merged**
